apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: spring-web-socket-keycloak
  labels:     
    provider: stakater
    version: "1.0.0"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-web-socket-keycloak
    spec:
      containers:
      - name: spring-web-socket-keycloak
        image: "stakater/spring-web-socket-keycloak:maven-centos3.5.4-jdk1.8-centos7-SNAPSHOT-feature-websocket-2"
        ports:
        - containerPort: 8080
---

kind: Service
apiVersion: v1
metadata:
  annotations:
    xposer.stakater.com/annotations: |-
       kubernetes.io/ingress.class: external-ingress
       ingress.kubernetes.io/force-ssl-redirect: false
       certmanager.k8s.io/cluster-issuer: letsencrypt-production
    config.xposer.stakater.com/IngressURLTemplate: "{{ `socketapp.lab.{{.Domain}}` }}"
    config.xposer.stakater.com/Domain: stackator.com
    config.xposer.stakater.com/TLS: "true"
    config.xposer.stakater.com/IngressNameTemplate: "{{ `akah-{{.Service}}-{{.Namespace}}` }}"
  labels:
    k8sapp: stakater-monitoring
    customLabel: present
    expose: 'true'
  name: socketapp
spec:
  selector:
    app: spring-web-socket-keycloak
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
---